### ISSUE TITLE
Incorrect result (decimal digits are missing)

### ISSUE THREAD

**Issue by lorihompoth** [virgil-av/numbers-to-words-romanian#13]
The decimal digits are missing in some specific cases. For example: 
`generateWords(120.5) // o sută douăzeci`
`generateWords(130.5) // o sută treizeci`
`generateWords(140.5) // o sută patruzeci`
`generateWords(150.5) // o sută cincizeci`
`generateWords(160.5) // o sută șaizeci`
`generateWords(170.5) // o sută șaptezeci`
`generateWords(180.5) // o sută optzeci`
`generateWords(190.5) // o sută nouăzeci`

**Comment by virgil-av** [comment]
This library does not cover decimals, was intended to be as lightweight as possible with less complexity,  if you wish to expand the library you can create a PR (will not accept without test cases) or just fork it and modify it to your own convenience.

In the meantime you can create a function to adapt it to your needs, example below.

given input 120.5

```
function processDecimalNumbers(number) {
    let integerInput  = number.toString().split(".")[0]; // this will be 120
    let floatInput = number.toString().split(".")[1]  // this will be 5

    return (generateWords(+integerInput) + " virgulă " + generateWords(+floatInput))  // + converting string back to integer
}
```

You might want to expand the above function with a switch case for example

.5 to add a 0 at the end ->  .50
.05 in this case the 0 before 5 will be ignored so you need to add it manually   "zero" + generateWords(floatInput)
